name: car_rent
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  bloc_test: ^10.0.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.9.0
  dots_indicator: ^4.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localization: ^0.3.3
  get_it: ^8.2.0
  http: ^1.5.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  lottie: ^3.3.1
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.7.2
  shared_preferences: ^2.5.3
  syncfusion_flutter_datepicker: ^31.1.19
  equatable: ^2.0.7
  cached_network_image: ^3.4.1
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true # <<<<<< مهم جدا عشان l10n تشتغل

  assets:
    - lib/assets/images/

gen-l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
